# Generated by Django 3.1.7 on 2021-03-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0005_authorreview_bookreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorReview',
            new_name='Review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='librarian.book'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
